name: "Understanding context 01"
on: push
jobs: 
    event-info-job:
        runs-on: ubuntu-latest
        steps: 
            - name: Print Trigger events
              run: echo "My trigger event is ${{ github.event_name }}  event " 
