name: 03 - Understanding Runners
on: push
jobs: 
    runner-info-job:
        runs-on: ubuntu-latest
        steps:
            - name: print runner details
              run: | 
                echo "Workflow is executing on a github hosted runner"
                echo "RUnner Name : $RUNNER_NAME"
                echo  "RunnEr os: $RUNNER_OS"
                echo "Runner architecture is : $RUNNER_ARCH"