name: 04 understanding runners 
on: push
jobs: 
    windows-runner-job:
        runs-on: windows-latest
        steps:
            - name: Print windows runner details

              shell: bash
              run: | 
               echo "RUnner Name : $RUNNER_NAME"
               echo  "RunnEr os: $RUNNER_OS"
               echo "Runner architecture is : $RUNNER_ARCH"